baseURL = "https://ordagofilms.com"
title = "Órdago Films"
author = "username"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]

  showBlog = false
  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo-tiza.png"
    alt = "Órdago Films Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-24"

  [params.site]
    name = "Órdago Films"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Órdago Films es una productora audiovisual independiente que se especializa en la realización de cortometrajes y documentales."
    meta_og_title = "Órdago Films"
    meta_og_type = "website"
    meta_og_url = "https://ordagofilms.com"
    meta_og_image = "https://ordagofilms.com/img/who/camara.jpeg"
    meta_og_description = "Órdago Films"
    meta_twitter_card = "summary_large_image"

  [params.seo]
    description = "Órdago Films - Productora audiovisual en Madrid. Especializada en vídeos corporativos, documentales y contenido digital."
    site_name = "Órdago Films"
    type = "website"
    locale = "es_ES"
    twitter_card = "summary_large_image"
    canonical = "https://ordagofilms.com"
[menu]

  [[menu.main]]
    identifier = "projects"
    name = "Producciones"
    url = "/projects/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Artículos"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "Quiénes Somos"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contact/"
    weight = 4


